# Generated by Django 3.2.6 on 2021-09-26 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodectModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dic', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='prodect/image')),
                ('catagre', models.CharField(choices=[('k', 'kurti'), ('l', 'leggings'), ('j', 'jeans')], max_length=50)),
            ],
        ),
    ]
