# Generated by Django 3.2.6 on 2021-09-26 08:07

from django.db import migrations, models
import prodect.models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodectmodels',
            name='image',
            field=models.ImageField(upload_to=prodect.models.fileName),
        ),
    ]
