# Generated by Django 3.2.6 on 2021-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0002_alter_prodectmodels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodectmodels',
            name='L',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodectmodels',
            name='M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodectmodels',
            name='S',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodectmodels',
            name='x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodectmodels',
            name='xl',
            field=models.BooleanField(default=False),
        ),
    ]
