# Generated by Django 3.2.6 on 2021-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0003_auto_20210926_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodectmodels',
            name='xxl',
            field=models.BooleanField(default=False),
        ),
    ]
