# Generated by Django 3.2.6 on 2021-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0004_prodectmodels_xxl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodectmodels',
            old_name='x',
            new_name='X',
        ),
        migrations.RenameField(
            model_name='prodectmodels',
            old_name='xl',
            new_name='XL',
        ),
        migrations.RenameField(
            model_name='prodectmodels',
            old_name='xxl',
            new_name='XXL',
        ),
    ]
