# Generated by Django 3.2.6 on 2021-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0005_auto_20210926_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='L',
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='M',
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='S',
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='X',
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='XL',
        ),
        migrations.RemoveField(
            model_name='prodectmodels',
            name='XXL',
        ),
        migrations.AddField(
            model_name='prodectmodels',
            name='size',
            field=models.ManyToManyField(related_name='Size', to='prodect.Size'),
        ),
    ]
