# Generated by Django 3.2.6 on 2021-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0007_auto_20210926_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='Color',
            field=models.CharField(max_length=50),
        ),
    ]
