# Generated by Django 3.2.6 on 2021-09-26 09:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0008_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='Color',
            field=colorfield.fields.ColorField(default='#ffff', max_length=18),
        ),
    ]
